name = "xr-awards"
main = "dist/_worker.js/index.js"
compatibility_date = "2025-10-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true
