/**
 * Tags API Endpoint
 * GET /api/tags - List all tags
 * POST /api/tags - Create a tag
 * PUT /api/tags - Update a tag
 * DELETE /api/tags - Delete a tag
 */

import type { APIRoute } from 'astro';
import { createServerClient } from '@supabase/ssr';

// Helper to initialize Supabase client
function getSupabaseClient(cookies: any) {
  return createServerClient(
    import.meta.env.SUPABASE_URL,
    import.meta.env.SUPABASE_ANON_KEY,
    {
      cookies: {
        get(key: string) {
          return cookies.get(key)?.value;
        },
        set(key: string, value: string, options: any) {
          cookies.set(key, value, options);
        },
        remove(key: string, options: any) {
          cookies.delete(key, options);
        },
      },
    }
  );
}

// Helper to check authentication
async function checkAuth(cookies: any) {
  const supabase = getSupabaseClient(cookies);
  const { data: { session }, error } = await supabase.auth.getSession();
  
  if (error || !session) {
    return { authenticated: false, supabase, session: null };
  }
  
  return { authenticated: true, supabase, session };
}

// GET - List all tags
export const GET: APIRoute = async ({ cookies }) => {
  try {
    const { authenticated, supabase } = await checkAuth(cookies);
    
    if (!authenticated) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const { data, error } = await supabase
      .from('tags')
      .select('*')
      .order('name', { ascending: true });

    if (error) throw error;

    return new Response(
      JSON.stringify({ tags: data }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('GET tags error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Failed to fetch tags' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

// POST - Create a tag
export const POST: APIRoute = async ({ request, cookies }) => {
  try {
    const { authenticated, supabase } = await checkAuth(cookies);
    
    if (!authenticated) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const body = await request.json();
    const { name, description } = body;

    if (!name) {
      return new Response(
        JSON.stringify({ error: 'Name is required' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    // Slug will be auto-generated by the database trigger
    const { data, error } = await supabase
      .from('tags')
      .insert({ name, description })
      .select()
      .single();

    if (error) throw error;

    return new Response(
      JSON.stringify({ tag: data, message: 'Tag created successfully' }),
      { status: 201, headers: { 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('POST tags error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Failed to create tag' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

// PUT - Update a tag
export const PUT: APIRoute = async ({ request, cookies }) => {
  try {
    const { authenticated, supabase } = await checkAuth(cookies);
    
    if (!authenticated) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const body = await request.json();
    const { id, name, description } = body;

    if (!id) {
      return new Response(
        JSON.stringify({ error: 'ID is required' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const { data, error } = await supabase
      .from('tags')
      .update({ name, description })
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;

    return new Response(
      JSON.stringify({ tag: data, message: 'Tag updated successfully' }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('PUT tags error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Failed to update tag' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

// DELETE - Delete a tag
export const DELETE: APIRoute = async ({ request, cookies }) => {
  try {
    const { authenticated, supabase } = await checkAuth(cookies);
    
    if (!authenticated) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const body = await request.json();
    const { id } = body;

    if (!id) {
      return new Response(
        JSON.stringify({ error: 'ID is required' }),
        { status: 400, headers: { 'Content-Type': 'application/json' } }
      );
    }

    const { error } = await supabase
      .from('tags')
      .delete()
      .eq('id', id);

    if (error) throw error;

    return new Response(
      JSON.stringify({ message: 'Tag deleted successfully' }),
      { status: 200, headers: { 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('DELETE tags error:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Failed to delete tag' }),
      { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
};

